//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotatoCornerSys
{
    public partial class ActivityLog
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton lnkSales;
        protected global::System.Web.UI.WebControls.LinkButton lnkUpdate;
        protected global::System.Web.UI.WebControls.LinkButton lnkActivityLog;
        protected global::System.Web.UI.WebControls.LinkButton lnkProfile;
        protected global::System.Web.UI.WebControls.DropDownList ddlActivityType;
        protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblLogCount;
        protected global::System.Web.UI.WebControls.GridView gvActivityLog;
    }
}
